### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by ldeluigi** [EasyDesk/easydesk-clean-architecture#66]
# Tasks
- [ ] https://github.com/EasyDesk/easydesk-clean-architecture/issues/64
- [ ] Setting Allowed-Hosts
- [ ] Static code analysis (ex. CodeQL, Sonarcloud)
  - One problem would be supported language versions. A solution could be running during periods of versions alignment between compiler and analisys tool
  - Another problem: security mode vs. security+quality mode

## References
* https://learn.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-7.0

**Comment by ldeluigi** [comment]
Done with 0ffa0aff50d0f2572272feea8ac481ea57dfa998
